name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: deeprave/actions/test@v1
        with:
          python-version: '3.13'
